include: package:flutter_lints/flutter.yaml
linter:
  rules:
    use_build_context_synchronously: false
    no_leading_underscores_for_local_identifiers: false
    constant_identifier_names: false
    prefer_const_declarations: false
